version: '2.1'
services:
  nginx:
    build: docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/logs/:/var/log/nginx
      - "./source:/var/www/source"
  php:
    build: docker/php
    restart: always
    volumes:
      - "./source:/var/www/source"
  composer:
    image: composer:1.7.2
    volumes:
      - "./source:/app"
    command: install
